@echo off
echo Переносим обновленный index.html с ветки master на ветку main...

echo Переключаемся на ветку master...
git checkout master

echo Копируем index.html...
copy index.html index_updated.html

echo Переключаемся на ветку main...
git checkout main

echo Заменяем index.html на обновленную версию...
copy index_updated.html index.html

echo Добавляем изменения...
git add index.html

echo Создаем коммит...
git commit -m "Обновлен index.html с правильными ценами и товарами"

echo Удаляем временный файл...
del index_updated.html

echo Готово! index.html обновлен на ветке main.
pause
