services:
  - type: web
    name: daryrei-bot
    env: python
    pythonVersion: 3.9.18
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn bot:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: BOT_TOKEN
        value: 8121877943:AAEPprLrwI627XQd9Al7CQGTLvQtyopRKcE
      - key: ORDER_GROUP_ID
        value: "-1003025937033"
